### ISSUE TITLE
Remove "PBS -V" from dev driver scripts

### ISSUE THREAD

**Issue by malloryprow** [NOAA-EMC/EVS#464]
I was having issues running on Dogwood so I emailed the helpdesk. In their debugging of what was doing on they noted this

> We do _not_ recommend using the "-V" flag with qsub since it consumes a large amount of memory for the job data (slowing down server requests when many jobs do this) and can inadvertently impact the job execution, which is what appears to have happened here.

We should remove the "#PBS -V" lines from all the dev driver scripts that have it.

**Comment by AliciaBentley-NOAA** [comment]
@malloryprow That sounds good to me. We recently (in Perry's PR) removed "#PBS -V" line from NCO's .ecf scripts. If EVS runs fine without "#PBS -V", I think we can safely remove it from all dev drivers. 

@PerryShafran-NOAA @ShelleyMelchior-NOAA Thoughts?
