### ISSUE TITLE
wafs: Update for WAFS v7.0 implementation

### ISSUE THREAD

**Issue by YaliMao-NOAA** [NOAA-EMC/EVS#506]
1. use EVS v1.0.14 when updating EVS to adjust to new path/file names of WAFS v7.0

Redmine tasks:
https://vlab.noaa.gov/redmine/issues/130581
https://vlab.noaa.gov/redmine/issues/130582

**Comment by malloryprow** [comment]
Thanks for making this issue, Yali! Looking forward to your PR!

**Comment by AliciaBentley-NOAA** [comment]
Note: EVS will be upgraded to EVS v1.0.11 when RTOFS v2.4 becomes operational during the second week of September because the RTOFS version number will need to be upgraded in EVS's run.ver file. That means that the WAFS upgrade to EVS will ultimately be **EVS v1.0.12**!

CC @malloryprow @YaliMao-NOAA

**Comment by YaliMao-NOAA** [comment]
As updated from @malloryprow on Sep 17 2024, WAFS upgrade will be in EVS v1.0.14

**Comment by YaliMao-NOAA** [comment]
@malloryprow @AliciaBentley-NOAA 
I checked out release/evs.v1.0.14. I think I don't need to pick up changes which are already in develop branch, right? For example in dev/drivers/scripts/stats/wafs/jevs_wafs_atmos_stats.sh:
1. Change from "#PBS -A EVS-DEV" to "#PBS -A VERF-DEV"
2. Remove "#PBS -V"
etc.
Instead, changes made in evs.v1.0.14 will be merged to develop, right?

**Comment by malloryprow** [comment]
Please submit to release/evs.v1.0.14.

We can work to bring the changes into develop closer to implementation.

**Comment by malloryprow** [comment]
You can test and develop using "#PBS -A VERF-DEV". You can keep "#PBS -V".

**Comment by AliciaBentley-NOAA** [comment]
@YaliMao-NOAA @malloryprow Quick note to keep in mind: NCO has requested that we only make the changes to the filenames/paths that are absolutely necessary for EVS v1.0.14 to work with WAFS v7.0 files. No other changes from the current operational configuration are allowed in this EVS release (and NCO will do a "diff" of the current ops package and the EVS v1.0.14 package to check). The EVS develop branch is building toward EVS v2.0 right now, so those changes should not be included in EVS v1.0.14. Thanks, Yali!

**Comment by YaliMao-NOAA** [comment]
@AliciaBentley-NOAA @malloryprow Got it! Thank you!

**Comment by malloryprow** [comment]
Yup! Let us know if you have anymore questions!

**Comment by YaliMao-NOAA** [comment]
Sorry, another question.

The operational folder for WAFS is: com/gfs/v16.3/gfs.20240922/00/atmos
The incoming WAFS separation is: com/wafs/v7.0/wafs.20240922/00. Under this folder, files are saved in different subfolders as (which Rahul told me this is going to the future of GFS, files will be saved in subfolders defined by the jobs):
├── gcip
├── grib
│   └── wmo
├── grib2
│   ├── 0p25
│   │   └── blending
│   │       └── wmo
│   └── 1p25
│       └── wmo
└── upp

I can take care of these subfolders in the scripts. My question is: must RUN be assigned a value in EVS? If so, what should the value of RUN? Currently it is "export RUN=${RUN:-atmos}".

**Comment by malloryprow** [comment]
Yes, it should be assigned. RUN should remain "atmos" for the EVS WAFS stats job.

**Comment by YaliMao-NOAA** [comment]
Can I keep forecast hours in 2 digits for WAFS EVS?

**Comment by malloryprow** [comment]
I would say if it is what you need to do to get EVS working with WAFS v7.0 then I would do that. The only changes to the code should be to support EVS working with WAFS v7.0.

**Comment by YaliMao-NOAA** [comment]
Got it. I am going to make a PR. I tested twice on different days last week but haven't gotten a chance to compare to the operational one. I will update the PR later if needed
