### ISSUE TITLE
aqm: Address Bugzilla 1547 - MPMD processes share the same working directory

### ISSUE THREAD

**Issue by malloryprow** [NOAA-EMC/EVS#550]
From NCO's Bugzilla 1547

> Multiple jobs use shared working directory for MPMD. Please modify the scripts to have isolated working directory for each process. 
> 
> In the case of extreme IO, please work with NCO/GDIT for the best approach.

More information can be found [here](https://docs.google.com/document/d/12UlvHV89xm_Y6_ayVjFngHQ8I0y77Y_3VJYgzLvLbak/edit).

**Suspected aqm Jobs Using MPMD**

**Comment by malloryprow** [comment]
Looking over [exevs_aqm_grid2obs_plots.sh](https://github.com/NOAA-EMC/EVS/blob/develop/scripts/plots/aqm/exevs_aqm_grid2obs_plots.sh) it does look like a serial job to me. 

I'm going to close this PR for aqm then.

I can add to the Fixes and Additions to update the resources used for this job.

**Comment by Ho-ChunHuang-NOAA** [comment]
Mallory, Thanks.   I will change the CPU to 1 and do some testing.  If all goes well, I will submit a PR to update the cpu number in EVS v2.0.

**Comment by malloryprow** [comment]
Fantastic!
