### ISSUE TITLE
wafs: Address Bugzilla 1547 - MPMD processes share the same working directory

### ISSUE THREAD

**Issue by malloryprow** [NOAA-EMC/EVS#562]
From NCO's Bugzilla 1547

> Multiple jobs use shared working directory for MPMD. Please modify the scripts to have isolated working directory for each process. 
> 
> In the case of extreme IO, please work with NCO/GDIT for the best approach.

More information can be found [here](https://docs.google.com/document/d/12UlvHV89xm_Y6_ayVjFngHQ8I0y77Y_3VJYgzLvLbak/edit).

**Suspected wafs Jobs Using MPMD**

- [x] stats/wafs/jevs_wafs_atmos_stats.sh

**Comment by malloryprow** [comment]
Sorry, @YaliMao-NOAA please ignore. This GitHub issue is not assigned to you. I removed you!

**Comment by YaliMao-NOAA** [comment]
@malloryprow It's ok. I remember the issue addressed by the bugzilla was brought up when I was developing WAFS EVS. It was solved at that time.
