### ISSUE TITLE
aqm: Address Bugzilla 1606 - counting of models in python scripts

### ISSUE THREAD

**Issue by malloryprow** [NOAA-EMC/EVS#626]
On 20241228, evs_mesoscale_sref_cape_past90days_plots failed with the following error.

Traceback (most recent call last):

>   File "/lfs/h1/ops/prod/packages/evs.v1.0.15/ush/mesoscale/ush_sref_plot_py/lead_average.py", line 1622, in <module>
>     main()
>   File "/lfs/h1/ops/prod/packages/evs.v1.0.15/ush/mesoscale/ush_sref_plot_py/lead_average.py", line 1475, in main
>     plot_lead_average(
>   File "/lfs/h1/ops/prod/packages/evs.v1.0.15/ush/mesoscale/ush_sref_plot_py/lead_average.py", line 707, in plot_lead_average
>     if math.isinf(y_mod_min):
> UnboundLocalError: local variable 'y_mod_min' referenced before assignment

Please double check all scripts and fix if needed in the next upgrade:

- [x] ./ush/aqm/valid_hour_average.py
- [x] ./ush/aqm/threshold_average.py
- [x] ./ush/aqm/time_series.py
- [x] ./ush/aqm/lead_average.py

See #624 for what was delivered to fix the failed job.

**Comment by Ho-ChunHuang-NOAA** [comment]
I only see changes for one file in this commits

https://github.com/NOAA-EMC/EVS/pull/624/files/6d50f3e99996eb932f1e627669bc96de1a35fb08..17d318454385ff2da559157815c46859c08a7df7

Is this correct?  You listed 4 files above.

**Comment by malloryprow** [comment]
Correct. The changes were only done for 1 file to fix an operational failure of jevs_mesoscale_sref_cape_past90days_plots. No other components failed as of today.

 Developers need to double check their scripts if they are employing a similar logic to cause the failure and fix for EVS v2.0.

**Comment by Ho-ChunHuang-NOAA** [comment]
Hi, Mallory:

I checked and the changes in PR#624 has been applied to aqm lead-by_average.py
~/ush/aqm/lead_average.py

Lines 694-695 and 739-742

**Comment by malloryprow** [comment]
Ah, yes I see that.

**Comment by Ho-ChunHuang-NOAA** [comment]
All four files in aqm have been checked and the changes are already there.

 ./ush/aqm/valid_hour_average.py
 ./ush/aqm/threshold_average.py
 ./ush/aqm/time_series.py
 ./ush/aqm/lead_average.py
